---
resources:
- name: fun-with-concourse
  type: git
  source:
    uri: https://github.com/mShahidAslam/fun-with-concourse.git
    branch: master

jobs:
- name: smoke
  plan:
  - get: fun-with-concourse
    trigger: true
  - task: say-hello
    file: fun-with-concourse/smoke.yml
